/**
 * SaveState Design System — Quest Template Definitions
 *
 * Daily quests (5/day), Weekly quests (3/week), Story quests (5 chapters × 10 quests = 50).
 * Each quest has: id, type, title (UA), description (UA), target, xpReward, coinReward,
 * optional chapter, and iconName.
 */

// ── Quest Type ─────────────────────────────────────────────────
export type QuestType = 'daily' | 'weekly' | 'story';

// ── Quest Difficulty ───────────────────────────────────────────
export type QuestDifficulty = 'easy' | 'medium' | 'hard' | 'boss';

// ── Quest Definition ───────────────────────────────────────────
export interface QuestTemplate {
  /** Unique quest identifier */
  id: string;
  /** Quest category */
  type: QuestType;
  /** Ukrainian title */
  title: string;
  /** Ukrainian description */
  description: string;
  /** Number of actions required to complete */
  target: number;
  /** XP awarded on completion */
  xpReward: number;
  /** Coins awarded on completion */
  coinReward: number;
  /** Story chapter (only for type: 'story') */
  chapter?: number;
  /** Story chapter title (UA) */
  chapterTitle?: string;
  /** Lucide icon name */
  iconName: string;
  /** Difficulty level */
  difficulty: QuestDifficulty;
  /** Whether this quest can be repeated */
  repeatable: boolean;
}

// ── Daily Quests (5 per day) ───────────────────────────────────
export const dailyQuests: ReadonlyArray<QuestTemplate> = [
  {
    id: 'daily_first_step',
    type: 'daily',
    title: 'Перший крок',
    description: 'Зробіть першу транзакцію дня',
    target: 1,
    xpReward: 25,
    coinReward: 10,
    iconName: 'footprints',
    difficulty: 'easy',
    repeatable: false,
  },
  {
    id: 'daily_precision',
    type: 'daily',
    title: 'Точність',
    description: 'Запишіть 3 транзакції з точними сумами',
    target: 3,
    xpReward: 40,
    coinReward: 20,
    iconName: 'crosshair',
    difficulty: 'easy',
    repeatable: false,
  },
  {
    id: 'daily_discipline',
    type: 'daily',
    title: 'Дисципліна',
    description: 'Не витрачайте з основного бюджету 6 годин поспіль',
    target: 6,
    xpReward: 60,
    coinReward: 30,
    iconName: 'timer',
    difficulty: 'medium',
    repeatable: false,
  },
  {
    id: 'daily_marathoner',
    type: 'daily',
    title: 'Марафонець',
    description: 'Збережіть понад 100 ₴ за один день',
    target: 100,
    xpReward: 50,
    coinReward: 25,
    iconName: 'running',
    difficulty: 'medium',
    repeatable: false,
  },
  {
    id: 'daily_surprise',
    type: 'daily',
    title: 'Сюрприз',
    description: 'Виконайте випадковий бонусний квест',
    target: 1,
    xpReward: 35,
    coinReward: 50,
    iconName: 'gift',
    difficulty: 'easy',
    repeatable: false,
  },
];

// ── Weekly Quests (3 per week) ─────────────────────────────────
export const weeklyQuests: ReadonlyArray<QuestTemplate> = [
  {
    id: 'weekly_warrior',
    type: 'weekly',
    title: 'Тижневий воїн',
    description: 'Виконайте всі щоденні квести протягом 5 днів',
    target: 5,
    xpReward: 300,
    coinReward: 150,
    iconName: 'swords',
    difficulty: 'hard',
    repeatable: false,
  },
  {
    id: 'weekly_collector',
    type: 'weekly',
    title: 'Збирач',
    description: 'Додайте транзакції у 4 різні категорії за тиждень',
    target: 4,
    xpReward: 200,
    coinReward: 100,
    iconName: 'backpack',
    difficulty: 'medium',
    repeatable: false,
  },
  {
    id: 'weekly_strategist',
    type: 'weekly',
    title: 'Стратег',
    description: 'Досягніть щотижневої мети заощаджень на 80%',
    target: 80,
    xpReward: 350,
    coinReward: 200,
    iconName: 'chess',
    difficulty: 'hard',
    repeatable: false,
  },
];

// ── Story Quests: 5 chapters × 10 quests ──────────────────────
const storyChapter1Title = 'Розділ 1: Початок шляху';
const storyChapter2Title = 'Розділ 2: Битва за бюджет';
const storyChapter3Title = 'Розділ 3: Мистецтво накопичення';
const storyChapter4Title = 'Розділ 4: Стратегія фінансової фортеці';
const storyChapter5Title = 'Розділ 5: Шлях до фінансової свободи';

export const storyQuests: ReadonlyArray<QuestTemplate> = [
  // ══ Chapter 1: Початок шляху ════════════════════════════════
  {
    id: 'story_1_01',
    type: 'story',
    title: 'Перше знайомство',
    description: 'Завершіть реєстрацію та налаштуйте профіль',
    target: 1,
    xpReward: 50,
    coinReward: 25,
    chapter: 1,
    chapterTitle: storyChapter1Title,
    iconName: 'user-plus',
    difficulty: 'easy',
    repeatable: false,
  },
  {
    id: 'story_1_02',
    type: 'story',
    title: 'Перша запис',
    description: 'Додайте свою першу транзакцію',
    target: 1,
    xpReward: 30,
    coinReward: 15,
    chapter: 1,
    chapterTitle: storyChapter1Title,
    iconName: 'pencil',
    difficulty: 'easy',
    repeatable: false,
  },
  {
    id: 'story_1_03',
    type: 'story',
    title: 'Перші заощадження',
    description: 'Збережіть перші 500 ₴',
    target: 500,
    xpReward: 75,
    coinReward: 40,
    chapter: 1,
    chapterTitle: storyChapter1Title,
    iconName: 'piggy-bank',
    difficulty: 'easy',
    repeatable: false,
  },
  {
    id: 'story_1_04',
    type: 'story',
    title: 'Дослідник категорій',
    description: 'Створіть 3 категорії транзакцій',
    target: 3,
    xpReward: 40,
    coinReward: 20,
    chapter: 1,
    chapterTitle: storyChapter1Title,
    iconName: 'folder-plus',
    difficulty: 'easy',
    repeatable: false,
  },
  {
    id: 'story_1_05',
    type: 'story',
    title: 'Перша серія',
    description: 'Ведіть записи 3 дні поспіль',
    target: 3,
    xpReward: 60,
    coinReward: 30,
    chapter: 1,
    chapterTitle: storyChapter1Title,
    iconName: 'flame',
    difficulty: 'medium',
    repeatable: false,
  },
  {
    id: 'story_1_06',
    type: 'story',
    title: 'Перший квест',
    description: 'Виконайте 1 щоденний квест',
    target: 1,
    xpReward: 35,
    coinReward: 15,
    chapter: 1,
    chapterTitle: storyChapter1Title,
    iconName: 'scroll',
    difficulty: 'easy',
    repeatable: false,
  },
  {
    id: 'story_1_07',
    type: 'story',
    title: 'Фінансова мета',
    description: 'Створіть свою першу ціль заощаджень',
    target: 1,
    xpReward: 50,
    coinReward: 25,
    chapter: 1,
    chapterTitle: storyChapter1Title,
    iconName: 'target',
    difficulty: 'easy',
    repeatable: false,
  },
  {
    id: 'story_1_08',
    type: 'story',
    title: 'Перший тиждень',
    description: 'Зробіть 10 транзакцій за один тиждень',
    target: 10,
    xpReward: 80,
    coinReward: 40,
    chapter: 1,
    chapterTitle: storyChapter1Title,
    iconName: 'calendar-check',
    difficulty: 'medium',
    repeatable: false,
  },
  {
    id: 'story_1_09',
    type: 'story',
    title: 'Перше досягнення',
    description: 'Отримайте своє перше досягнення',
    target: 1,
    xpReward: 45,
    coinReward: 50,
    chapter: 1,
    chapterTitle: storyChapter1Title,
    iconName: 'award',
    difficulty: 'easy',
    repeatable: false,
  },
  {
    id: 'story_1_10',
    type: 'story',
    title: 'Новачок-воїн',
    description: 'Досягніть 2 рівня',
    target: 2,
    xpReward: 100,
    coinReward: 60,
    chapter: 1,
    chapterTitle: storyChapter1Title,
    iconName: 'shield',
    difficulty: 'medium',
    repeatable: false,
  },

  // ══ Chapter 2: Битва за бюджет ══════════════════════════════
  {
    id: 'story_2_01',
    type: 'story',
    title: 'Бюджетний щит',
    description: 'Встановіть ліміт витрат на категорію',
    target: 1,
    xpReward: 60,
    coinReward: 30,
    chapter: 2,
    chapterTitle: storyChapter2Title,
    iconName: 'shield-alert',
    difficulty: 'medium',
    repeatable: false,
  },
  {
    id: 'story_2_02',
    type: 'story',
    title: 'Уламок уламка',
    description: 'Збережіть 2000 ₴ загалом',
    target: 2000,
    xpReward: 100,
    coinReward: 50,
    chapter: 2,
    chapterTitle: storyChapter2Title,
    iconName: 'gem',
    difficulty: 'medium',
    repeatable: false,
  },
  {
    id: 'story_2_03',
    type: 'story',
    title: 'Квестовий мисливець',
    description: 'Виконайте 10 щоденних квестів',
    target: 10,
    xpReward: 120,
    coinReward: 60,
    chapter: 2,
    chapterTitle: storyChapter2Title,
    iconName: 'swords',
    difficulty: 'medium',
    repeatable: false,
  },
  {
    id: 'story_2_04',
    type: 'story',
    title: 'Серія з 7 днів',
    description: 'Ведіть записи 7 днів поспіль',
    target: 7,
    xpReward: 90,
    coinReward: 45,
    chapter: 2,
    chapterTitle: storyChapter2Title,
    iconName: 'flame',
    difficulty: 'medium',
    repeatable: false,
  },
  {
    id: 'story_2_05',
    type: 'story',
    title: 'Фінансовий аналітик',
    description: 'Перегляньте аналітику за тиждень',
    target: 1,
    xpReward: 40,
    coinReward: 20,
    chapter: 2,
    chapterTitle: storyChapter2Title,
    iconName: 'bar-chart-3',
    difficulty: 'easy',
    repeatable: false,
  },
  {
    id: 'story_2_06',
    type: 'story',
    title: 'Рівень 5',
    description: 'Досягніть 5 рівня',
    target: 5,
    xpReward: 150,
    coinReward: 75,
    chapter: 2,
    chapterTitle: storyChapter2Title,
    iconName: 'arrow-up-circle',
    difficulty: 'medium',
    repeatable: false,
  },
  {
    id: 'story_2_07',
    type: 'story',
    title: 'День без витрат',
    description: 'Протягом одного дня не записуйте жодних витрат',
    target: 1,
    xpReward: 80,
    coinReward: 40,
    chapter: 2,
    chapterTitle: storyChapter2Title,
    iconName: 'ban',
    difficulty: 'hard',
    repeatable: false,
  },
  {
    id: 'story_2_08',
    type: 'story',
    title: 'Майстер квестів',
    description: 'Виконайте 3 щотижневі квести',
    target: 3,
    xpReward: 130,
    coinReward: 65,
    chapter: 2,
    chapterTitle: storyChapter2Title,
    iconName: 'trophy',
    difficulty: 'hard',
    repeatable: false,
  },
  {
    id: 'story_2_09',
    type: 'story',
    title: 'Перші 5000 ₴',
    description: 'Загалом збережіть 5000 ₴',
    target: 5000,
    xpReward: 120,
    coinReward: 60,
    chapter: 2,
    chapterTitle: storyChapter2Title,
    iconName: 'wallet',
    difficulty: 'medium',
    repeatable: false,
  },
  {
    id: 'story_2_10',
    type: 'story',
    title: 'Захисник бюджету',
    description: 'Не перевищте жоден ліміт витрат за тиждень',
    target: 1,
    xpReward: 160,
    coinReward: 80,
    chapter: 2,
    chapterTitle: storyChapter2Title,
    iconName: 'shield-check',
    difficulty: 'hard',
    repeatable: false,
  },

  // ══ Chapter 3: Мистецтво накопичення ════════════════════════
  {
    id: 'story_3_01',
    type: 'story',
    title: 'Мистецтво економії',
    description: 'Збережіть 10000 ₴ загалом',
    target: 10000,
    xpReward: 200,
    coinReward: 100,
    chapter: 3,
    chapterTitle: storyChapter3Title,
    iconName: 'paintbrush',
    difficulty: 'medium',
    repeatable: false,
  },
  {
    id: 'story_3_02',
    type: 'story',
    title: 'Серія з 14 днів',
    description: 'Ведіть записи 14 днів поспіль',
    target: 14,
    xpReward: 150,
    coinReward: 75,
    chapter: 3,
    chapterTitle: storyChapter3Title,
    iconName: 'flame',
    difficulty: 'hard',
    repeatable: false,
  },
  {
    id: 'story_3_03',
    type: 'story',
    title: 'Колекціонер досягнень',
    description: 'Отримайте 10 досягнень',
    target: 10,
    xpReward: 180,
    coinReward: 90,
    chapter: 3,
    chapterTitle: storyChapter3Title,
    iconName: 'medal',
    difficulty: 'medium',
    repeatable: false,
  },
  {
    id: 'story_3_04',
    type: 'story',
    title: 'Рівень 10',
    description: 'Досягніть 10 рівня',
    target: 10,
    xpReward: 200,
    coinReward: 100,
    chapter: 3,
    chapterTitle: storyChapter3Title,
    iconName: 'trending-up',
    difficulty: 'hard',
    repeatable: false,
  },
  {
    id: 'story_3_05',
    type: 'story',
    title: 'Стратег цілей',
    description: 'Створіть 3 активні цілі заощаджень',
    target: 3,
    xpReward: 120,
    coinReward: 60,
    chapter: 3,
    chapterTitle: storyChapter3Title,
    iconName: 'target',
    difficulty: 'medium',
    repeatable: false,
  },
  {
    id: 'story_3_06',
    type: 'story',
    title: 'Квестовий ветеран',
    description: 'Виконайте 25 щоденних квестів',
    target: 25,
    xpReward: 180,
    coinReward: 90,
    chapter: 3,
    chapterTitle: storyChapter3Title,
    iconName: 'scroll-text',
    difficulty: 'hard',
    repeatable: false,
  },
  {
    id: 'story_3_07',
    type: 'story',
    title: 'Місяць дисципліни',
    description: 'Ведіть записи 30 днів поспіль',
    target: 30,
    xpReward: 250,
    coinReward: 125,
    chapter: 3,
    chapterTitle: storyChapter3Title,
    iconName: 'calendar',
    difficulty: 'hard',
    repeatable: false,
  },
  {
    id: 'story_3_08',
    type: 'story',
    title: 'Перша велика ціль',
    description: 'Досягніть 50% будь-якої цілі заощаджень',
    target: 50,
    xpReward: 150,
    coinReward: 75,
    chapter: 3,
    chapterTitle: storyChapter3Title,
    iconName: 'bullseye',
    difficulty: 'medium',
    repeatable: false,
  },
  {
    id: 'story_3_09',
    type: 'story',
    title: 'Майстер бюджету',
    description: 'Виконайте 10 щотижневих квестів',
    target: 10,
    xpReward: 220,
    coinReward: 110,
    chapter: 3,
    chapterTitle: storyChapter3Title,
    iconName: 'crown',
    difficulty: 'hard',
    repeatable: false,
  },
  {
    id: 'story_3_10',
    type: 'story',
    title: 'Архітектор багатства',
    description: 'Загалом збережіть 25000 ₴',
    target: 25000,
    xpReward: 250,
    coinReward: 125,
    chapter: 3,
    chapterTitle: storyChapter3Title,
    iconName: 'building',
    difficulty: 'hard',
    repeatable: false,
  },

  // ══ Chapter 4: Стратегія фінансової фортеці ═════════════════
  {
    id: 'story_4_01',
    type: 'story',
    title: 'Фінансова фортеця',
    description: 'Збережіть 50000 ₴ загалом',
    target: 50000,
    xpReward: 300,
    coinReward: 150,
    chapter: 4,
    chapterTitle: storyChapter4Title,
    iconName: 'castle',
    difficulty: 'hard',
    repeatable: false,
  },
  {
    id: 'story_4_02',
    type: 'story',
    title: 'Рівень 20',
    description: 'Досягніть 20 рівня',
    target: 20,
    xpReward: 300,
    coinReward: 150,
    chapter: 4,
    chapterTitle: storyChapter4Title,
    iconName: 'star',
    difficulty: 'hard',
    repeatable: false,
  },
  {
    id: 'story_4_03',
    type: 'story',
    title: 'Легенда досягнень',
    description: 'Отримайте 20 досягнень',
    target: 20,
    xpReward: 250,
    coinReward: 125,
    chapter: 4,
    chapterTitle: storyChapter4Title,
    iconName: 'award',
    difficulty: 'hard',
    repeatable: false,
  },
  {
    id: 'story_4_04',
    type: 'story',
    title: 'Тижневий чемпіон',
    description: 'Виконайте всі щоденні квести 7 днів поспіль',
    target: 7,
    xpReward: 280,
    coinReward: 140,
    chapter: 4,
    chapterTitle: storyChapter4Title,
    iconName: 'trophy',
    difficulty: 'hard',
    repeatable: false,
  },
  {
    id: 'story_4_05',
    type: 'story',
    title: 'Завершення цілі',
    description: 'Досягніть 100% будь-якої цілі заощаджень',
    target: 100,
    xpReward: 350,
    coinReward: 175,
    chapter: 4,
    chapterTitle: storyChapter4Title,
    iconName: 'check-circle-2',
    difficulty: 'hard',
    repeatable: false,
  },
  {
    id: 'story_4_06',
    type: 'story',
    title: 'Квестовий майстер',
    description: 'Виконайте 50 щоденних квестів',
    target: 50,
    xpReward: 300,
    coinReward: 150,
    chapter: 4,
    chapterTitle: storyChapter4Title,
    iconName: 'scroll-check',
    difficulty: 'hard',
    repeatable: false,
  },
  {
    id: 'story_4_07',
    type: 'story',
    title: 'Фінансовий стратег',
    description: 'Місяць не перевищуйте ліміти витрат',
    target: 30,
    xpReward: 350,
    coinReward: 175,
    chapter: 4,
    chapterTitle: storyChapter4Title,
    iconName: 'shield',
    difficulty: 'boss',
    repeatable: false,
  },
  {
    id: 'story_4_08',
    type: 'story',
    title: 'Золотий серп',
    description: 'Ведіть записи 60 днів поспіль',
    target: 60,
    xpReward: 400,
    coinReward: 200,
    chapter: 4,
    chapterTitle: storyChapter4Title,
    iconName: 'calendar-heart',
    difficulty: 'boss',
    repeatable: false,
  },
  {
    id: 'story_4_09',
    type: 'story',
    title: 'Збір коштовностей',
    description: 'Загалом збережіть 100000 ₴',
    target: 100000,
    xpReward: 450,
    coinReward: 225,
    chapter: 4,
    chapterTitle: storyChapter4Title,
    iconName: 'gem',
    difficulty: 'boss',
    repeatable: false,
  },
  {
    id: 'story_4_10',
    type: 'story',
    title: 'Фортрess completed',
    description: 'Завершіть усі квести глави 4',
    target: 1,
    xpReward: 500,
    coinReward: 300,
    chapter: 4,
    chapterTitle: storyChapter4Title,
    iconName: 'castle',
    difficulty: 'boss',
    repeatable: false,
  },

  // ══ Chapter 5: Шлях до фінансової свободи ════════════════════
  {
    id: 'story_5_01',
    type: 'story',
    title: 'Фінансова свобода',
    description: 'Збережіть 200000 ₴ загалом',
    target: 200000,
    xpReward: 500,
    coinReward: 250,
    chapter: 5,
    chapterTitle: storyChapter5Title,
    iconName: 'rocket',
    difficulty: 'boss',
    repeatable: false,
  },
  {
    id: 'story_5_02',
    type: 'story',
    title: 'Рівень 30',
    description: 'Досягніть 30 рівня',
    target: 30,
    xpReward: 400,
    coinReward: 200,
    chapter: 5,
    chapterTitle: storyChapter5Title,
    iconName: 'zap',
    difficulty: 'boss',
    repeatable: false,
  },
  {
    id: 'story_5_03',
    type: 'story',
    title: 'Всі досягнення',
    description: 'Отримайте 30 досягнень',
    target: 30,
    xpReward: 450,
    coinReward: 225,
    chapter: 5,
    chapterTitle: storyChapter5Title,
    iconName: 'award',
    difficulty: 'boss',
    repeatable: false,
  },
  {
    id: 'story_5_04',
    type: 'story',
    title: 'Серія з 90 днів',
    description: 'Ведіть записи 90 днів поспіль',
    target: 90,
    xpReward: 500,
    coinReward: 250,
    chapter: 5,
    chapterTitle: storyChapter5Title,
    iconName: 'flame',
    difficulty: 'boss',
    repeatable: false,
  },
  {
    id: 'story_5_05',
    type: 'story',
    title: 'Майстер цілей',
    description: 'Завершіть 5 цілей заощаджень',
    target: 5,
    xpReward: 450,
    coinReward: 225,
    chapter: 5,
    chapterTitle: storyChapter5Title,
    iconName: 'target',
    difficulty: 'boss',
    repeatable: false,
  },
  {
    id: 'story_5_06',
    type: 'story',
    title: '100 щоденних квестів',
    description: 'Виконайте 100 щоденних квестів',
    target: 100,
    xpReward: 500,
    coinReward: 250,
    chapter: 5,
    chapterTitle: storyChapter5Title,
    iconName: 'scroll',
    difficulty: 'boss',
    repeatable: false,
  },
  {
    id: 'story_5_07',
    type: 'story',
    title: '500000 ₑ збережень',
    description: 'Загалом збережіть 500000 ₴',
    target: 500000,
    xpReward: 600,
    coinReward: 300,
    chapter: 5,
    chapterTitle: storyChapter5Title,
    iconName: 'wallet',
    difficulty: 'boss',
    repeatable: false,
  },
  {
    id: 'story_5_08',
    type: 'story',
    title: 'Рівень 40',
    description: 'Досягніть 40 рівня',
    target: 40,
    xpReward: 600,
    coinReward: 300,
    chapter: 5,
    chapterTitle: storyChapter5Title,
    iconName: 'trending-up',
    difficulty: 'boss',
    repeatable: false,
  },
  {
    id: 'story_5_09',
    type: 'story',
    title: 'Гранд-майстер',
    description: 'Отримайте всі досягнення',
    target: 1,
    xpReward: 1000,
    coinReward: 500,
    chapter: 5,
    chapterTitle: storyChapter5Title,
    iconName: 'sparkles',
    difficulty: 'boss',
    repeatable: false,
  },
  {
    id: 'story_5_10',
    type: 'story',
    title: 'Фінансова свобода!',
    description: 'Ви досягли фінансової свободи. Вітаємо!',
    target: 1,
    xpReward: 2000,
    coinReward: 1000,
    chapter: 5,
    chapterTitle: storyChapter5Title,
    iconName: 'sun',
    difficulty: 'boss',
    repeatable: false,
  },
];

// ── All Quests Combined ────────────────────────────────────────
export const allQuests: ReadonlyArray<QuestTemplate> = [
  ...dailyQuests,
  ...weeklyQuests,
  ...storyQuests,
];

// ── Utility: Get quests by type ────────────────────────────────
export function getQuestsByType(type: QuestType): ReadonlyArray<QuestTemplate> {
  return allQuests.filter((q) => q.type === type);
}

// ── Utility: Get quests by chapter ─────────────────────────────
export function getStoryChapter(chapter: number): ReadonlyArray<QuestTemplate> {
  return storyQuests.filter((q) => q.chapter === chapter);
}

// ── Utility: Find quest by ID ──────────────────────────────────
export function getQuestById(id: string): QuestTemplate | undefined {
  return allQuests.find((q) => q.id === id);
}

// ── Difficulty Config ──────────────────────────────────────────
export const difficultyConfig: Record<QuestDifficulty, { label: string; color: string; xpMultiplier: number }> = {
  easy: { label: 'Легко', color: '#00FF88', xpMultiplier: 1 },
  medium: { label: 'Середньо', color: '#00AAFF', xpMultiplier: 1.5 },
  hard: { label: 'Складно', color: '#FF6B00', xpMultiplier: 2 },
  boss: { label: 'Бос', color: '#FF3B3B', xpMultiplier: 3 },
};
